services:
  news-crawler-server:
    image: devforma/news-crawler:latest
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env
    command: server

  news-crawler-worker:
    image: devforma/news-crawler:latest
    volumes:
      - ./.env:/app/.env
    command: crawler
    deploy:
      replicas: 2